# Generated by Django 3.2.6 on 2021-09-16 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('count', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Endpoint',
                'verbose_name_plural': 'Endpoints',
                'ordering': ['last_updated'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('index', models.IntegerField(null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(null=True)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.endpoint')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['index'],
            },
        ),
    ]
