# Generated by Django 3.2.6 on 2021-08-15 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokedex', '0002_delete_pokemon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('effect', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damage_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('info', models.TextField(null=True)),
                ('damage_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.damage_class')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.IntegerField(null=True)),
                ('base_experience', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('species', models.CharField(max_length=50, null=True)),
                ('official_artwork', models.ImageField(null=True, upload_to='')),
                ('hp', models.IntegerField(null=True)),
                ('attack', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('sp_attack', models.IntegerField(null=True)),
                ('sp_defense', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('abilities', models.ManyToManyField(to='pokedex.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('half_damage_against', models.ManyToManyField(blank=True, related_name='_pokedex_type_half_damage_against_+', to='pokedex.Type')),
                ('ineff_against', models.ManyToManyField(blank=True, related_name='_pokedex_type_ineff_against_+', to='pokedex.Type')),
                ('super_eff_against', models.ManyToManyField(blank=True, related_name='_pokedex_type_super_eff_against_+', to='pokedex.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('generation', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.type')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.version')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='versions',
            field=models.ManyToManyField(through='pokedex.Type_var', to='pokedex.Version'),
        ),
        migrations.CreateModel(
            name='Pokemon_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.ManyToManyField(to='pokedex.Move')),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon')),
                ('types', models.ManyToManyField(to='pokedex.Type')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.version')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='versions',
            field=models.ManyToManyField(through='pokedex.Pokemon_var', to='pokedex.Version'),
        ),
        migrations.CreateModel(
            name='Move_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('power', models.IntegerField(null=True)),
                ('accuracy', models.IntegerField(null=True)),
                ('pp', models.IntegerField(null=True)),
                ('priority', models.IntegerField(null=True)),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.move')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.type')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.version')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='versions',
            field=models.ManyToManyField(through='pokedex.Move_var', to='pokedex.Version'),
        ),
        migrations.CreateModel(
            name='Ability_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('is_present', models.BooleanField(null=True)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.ability')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokedex.version')),
            ],
        ),
        migrations.AddField(
            model_name='ability',
            name='versions',
            field=models.ManyToManyField(through='pokedex.Ability_var', to='pokedex.Version'),
        ),
    ]
