# Generated by Django 3.2.6 on 2021-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon_var',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ability_var',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='type_var',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
